ALTER TABLE "pg-drizzle_post" RENAME CONSTRAINT "pg-drizzle_post_createdById_user_id_fk" TO "pg-drizzle_post_createdById_user_id_fkey";--> statement-breakpoint
ALTER TABLE "resource" RENAME CONSTRAINT "resource_content_type_id_resource_content_type_id_fk" TO "resource_content_type_id_resource_content_type_id_fkey";--> statement-breakpoint
ALTER TABLE "resource" RENAME CONSTRAINT "resource_uploader_id_user_id_fk" TO "resource_uploader_id_user_id_fkey";--> statement-breakpoint
ALTER TABLE "resource" ALTER COLUMN "content_type_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "resource" ALTER COLUMN "uploader_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "country" DROP CONSTRAINT "country_created_by_id_user_id_fkey", ADD CONSTRAINT "country_created_by_id_user_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "country" DROP CONSTRAINT "country_updated_by_id_user_id_fkey", ADD CONSTRAINT "country_updated_by_id_user_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "degree_level" DROP CONSTRAINT "degree_level_created_by_id_user_id_fkey", ADD CONSTRAINT "degree_level_created_by_id_user_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "degree_level" DROP CONSTRAINT "degree_level_updated_by_id_user_id_fkey", ADD CONSTRAINT "degree_level_updated_by_id_user_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "field_of_study" DROP CONSTRAINT "field_of_study_created_by_id_user_id_fkey", ADD CONSTRAINT "field_of_study_created_by_id_user_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "field_of_study" DROP CONSTRAINT "field_of_study_updated_by_id_user_id_fkey", ADD CONSTRAINT "field_of_study_updated_by_id_user_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" DROP CONSTRAINT "pg-drizzle_post_createdById_user_id_fkey", ADD CONSTRAINT "pg-drizzle_post_createdById_user_id_fkey" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "resource" DROP CONSTRAINT "resource_content_type_id_resource_content_type_id_fkey", ADD CONSTRAINT "resource_content_type_id_resource_content_type_id_fkey" FOREIGN KEY ("content_type_id") REFERENCES "resource_content_type"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "resource" DROP CONSTRAINT "resource_uploader_id_user_id_fkey", ADD CONSTRAINT "resource_uploader_id_user_id_fkey" FOREIGN KEY ("uploader_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "round_event" DROP CONSTRAINT "round_event_created_by_id_user_id_fkey", ADD CONSTRAINT "round_event_created_by_id_user_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "round_event" DROP CONSTRAINT "round_event_updated_by_id_user_id_fkey", ADD CONSTRAINT "round_event_updated_by_id_user_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "scholarship_round" DROP CONSTRAINT "scholarship_round_created_by_id_user_id_fkey", ADD CONSTRAINT "scholarship_round_created_by_id_user_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "scholarship_round" DROP CONSTRAINT "scholarship_round_updated_by_id_user_id_fkey", ADD CONSTRAINT "scholarship_round_updated_by_id_user_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "scholarship" DROP CONSTRAINT "scholarship_created_by_id_user_id_fkey", ADD CONSTRAINT "scholarship_created_by_id_user_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL;--> statement-breakpoint
ALTER TABLE "scholarship" DROP CONSTRAINT "scholarship_updated_by_id_user_id_fkey", ADD CONSTRAINT "scholarship_updated_by_id_user_id_fkey" FOREIGN KEY ("updated_by_id") REFERENCES "user"("id") ON DELETE SET NULL;